--- 
branches: 
  only: 
    - master
dist: trusty
jdk: oraclejdk8
jobs: 
  include: 
    - 
      script: 
        - "echo \"Running battery of tests\""
      stage: "Build and Running Tests"
    - 
      install: true
      script: 
        - "echo \"Skipping tests\""
        - "mvn clean package -DskipTests"
        - "echo \"Instalation done\""
        - "echo \"We are going to run execute-on-vnc.sh and Sonar\""
        - "echo \"End Sonnar Excecution\""
      stage: "Build and Analyze"
language: java
