--- 
branches: 
  only: 
    - master
cache: 
  directories: 
    - $HOME/.m2/repository/
    - $HOME/.jmeter/
dist: trusty
jdk: oraclejdk8
jobs: 
  include: 
    - 
      script: 
        - "echo \"Running battery of tests\""
      stage: "Build and Running Tests"
    - 
      install: true
      script: 
        - "echo \"Skipping tests\""
        - "mvn clean package -DskipTests"
        - "echo \"Instalation done\""
        - "echo \"We are going to run execute-on-vnc.sh and Sonar\""
        - "echo \"End Sonnar Excecution\""
      stage: "Build and Analyze"
    - 
      install: true
      script: 
        - "echo \"Skipping tests\""
        - "mvn clean package -DskipTests"
        - "echo \"Instalation done\""
        - "echo \"Moving to Target\""
        - "cd target/jmeter-test"
        - "echo \"Excecuting tests\""
        - "JMETER_VERSION=5.0 sh testJmeter.sh"
        - "JMETER_VERSION=3.3 sh testJmeter.sh"
        - "JMETER_VERSION=4.0 sh testJmeter.sh"
        - "JMETER_VERSION=5.1 sh testJmeter.sh"
        - "JMETER_VERSION=5.1.1 sh testJmeter.sh"
        - "JMETER_VERSION=5.0 JVM_VERSION=11 sh testJmeter.sh"
      stage: "JMeter Compatibility"
    - 
      before_deploy: ~
      deploy: 
        api_key: $GH_TOKEN
        provider: releases
        skip_cleanup: true
        true: 
          branch: master
      install: true
      script: "echo \"Deploying to GitHub releases.\""
      stage: "GitHub Release"
language: java
