--- 
branches: 
  only: 
    - master
cache: 
  directories: 
    - $HOME/.m2/repository/
    - $HOME/.jmeter/
dist: trusty
env: "RUN_FIRST_JOB=1; RUN_SECOND_JOB=1"
jdk: oraclejdk8
jobs: 
  include: 
    - 
      if: "RUN_FIRST_JOB = 1"
      script: 
        - "echo \"Running battery of tests\""
      stage: "Build and Running Tests"
    - 
      install: true
      script: 
        - "mvn clean install -DskipTests"
        - ls
        - "cd target/"
        - ls
        - "cd target/jmeter-test"
        - "echo \"JMeter Compatibility\""
        - "JMETER_VERSION=5.0 sh testJmeter.sh"
        - "JMETER_VERSION=3.3 sh testJmeter.sh"
        - "JMETER_VERSION=4.0 sh testJmeter.sh"
        - "JMETER_VERSION=5.1 sh testJmeter.sh"
        - "JMETER_VERSION=5.1.1 sh testJmeter.sh"
        - "JMETER_VERSION=5.0 JVM_VERSION=11 sh testJmeter.sh"
      stage: "JMeter Compatibility"
    - 
      before_deploy: 
        - "export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}"
        - "git tag $TRAVIS_TAG"
      deploy: 
        api_key: $GH_TOKEN
        provider: releases
        skip_cleanup: true
        true: 
          branch: master
      file: 
        - target/jmeter-bzm-hls-*.jar
      install: true
      script: "echo \"Deploying to GitHub releases.\""
      stage: "GitHub Release"
language: java
