#TODO: Remember to delete all comments

#Seting up enviroment
language: java
dist: trusty
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository/"
  - "$HOME/.jmeter/"


#Install


before_deploy:
# - mvn --batch-mode versions:set -DnewVersion="$(T=${TRAVIS_TAG%%-lib}; echo ${T:1})"
#TODO: Review why the previous sentence break
  - echo "Some random text to test ECHO"
  - mvn --batch-mode versions:set -DnewVersion="2001" 
  - mvn clean package -DskipTests
  
deploy:
  provider: releases
  api_key: 
    secure: FBCNMPL5WRsBSuR3DDgpnU9yDDK8AGqP6IFcxcGRz0lbUfYeaM8Q0DB0nsaeoGmApabkYapWUul6E8BiJGn0n6/TeYzrfTy11aPz7mcI8lR535ASjhYCrdBU3JLPNq/tLHCI/H1/rJ6cxOqqmQPgfmD3e9QQ0HUx8Vr/eiV8iU2RLvKHkMJpYfLeFZqzHAMUgzAMNuHWnBYcujEoUb2B2uGwjy/m8tqP2YZm8HDFTJ41CufaUFVMteadXnWREcr5EcNp5EKfrTMe6+mjQ/2n4R4Zn7EaDZDBemjdx+EgA6rqrp7ESfnvtvzfGQBUsidCRzcEDQG2u2Q6tfCBwk1zcw9zacQFybSP4ayD3ohzUkjHX+i7I/dtk168w2RRF6ujVQAs+05PFBdUlR3iwCfUWn87cj5NASf8gsgkjCRht5T+StIK7vhBAc6B4uUEmzTjCBRFs3Rr3na6gaQZr1YCUi6bJU+L96oeHioKIrAdMAkLEgc4PEKYZDP5I3OIRA7Bm7vlVAM6vSX/kONCkOYaV1yY9ubxZ1qmUjPIKk+yGXHfCbGjnydCATg0ShCaRw501ndhj3nBajKNXvhsuPS6fgeTCo6lm89YvZfhhi6jbQa10pEKMxCtIYCyXSQNnCYTgnf1heYbVV9SXJx0tpIOD1CztUyvica5Q0kR94C8GlA=
  file_glob: true
  file: 
      - target/jmeter-bzm-hls-*.jar
  skip_cleanup: true
  on:
    repo: RicardoPoleo/HLSPlugin
    tags: true
    
  provider: script
  script: bash /execute-on-vnc.sh mvn --batch-mode clean install
      on:
      branch: master
  #script: bash /jmeter-plugins-build/scripts/execute-on-vnc.sh mvn --batch-mode clean install

# Errors:

# - mvn --batch-mode versions:set -DnewVersion="$(T=${TRAVIS_TAG%%-lib}; echo ${T:1})"
# Error result:
#[INFO] ------------------------------------------------------------------------
#[INFO] BUILD FAILURE
#[INFO] ------------------------------------------------------------------------
#[INFO] Total time: 7.426 s
#[INFO] Finished at: 2019-08-26T20:52:48Z
#[INFO] Final Memory: 17M/176M
#[INFO] ------------------------------------------------------------------------
#[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.7:set (default-cli) on project jmeter-hls: You must specify the new version, either by using the newVersion property (that is -DnewVersion=... on the command line) or run in interactive mode -> [Help 1]
#[ERROR] 
#[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#[ERROR] Re-run Maven using the -X switch to enable full debug logging.
#[ERROR] 
#[ERROR] For more information about the errors and possible solutions, please read the following articles:
#[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
#The command "mvn --batch-mode versions:set -DnewVersion="$(T=${TRAVIS_TAG%%-lib}; echo ${T:1})"" failed and exited with 1 during .
